create table curso(
    id bigint generated by default as identity primary key,
    nome varchar(50) not null,
    categoria varchar(50) not null
);

insert into curso values(1, 'Kotlin', 'Programacao');