create table usuario(
    id bigint generated by default as identity primary key,
    nome varchar(50) not null,
    email varchar(50) not null
);

insert into usuario values(1, 'Ana da Silva', 'ana@email.com');