create table resposta(
    id bigint generated by default as identity primary key,
    mensagem varchar(300) not null,
    data_criacao timestamp not null,
    topico_id bigint not null,
    autor_id bigint not null,
    solucao boolean not null,
    foreign key (topico_id) references topico(id),
    foreign key (autor_id) references usuario(id)
);